common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: webadmin
  password: og4pj97N3a
  host: 10.70.3.163

development:
  <<: *common
  database: forum
  username: postgres
  password: postgres
  host: localhost
  port: 5433
